import type { Diagnostic,MistakeCategory } from '../types';

type Education={category:MistakeCategory;conceptId?:string;plain:string;hints:[string,string]};

export function educateDiagnostic(diagnostic:Diagnostic):Diagnostic{
  const text=`${diagnostic.message} ${diagnostic.explanation}`.toLowerCase();
  const education=classify(text,diagnostic);
  return {...diagnostic,rawMessage:diagnostic.rawMessage??diagnostic.message,mistakeCategory:diagnostic.mistakeCategory??education.category,conceptId:diagnostic.conceptId??education.conceptId,explanation:education.plain,hints:diagnostic.hints??education.hints,suggestion:undefined};
}

function classify(text:string,diagnostic:Diagnostic):Education{
  if(text.includes('undefined control sequence'))return {category:'unknown-command',conceptId:'command',plain:'TeX встретил команду, определения которой нет в текущем контексте. Обычно причина — опечатка, неподключённый пакет или команда, доступная только в другом режиме.',hints:['Посмотрите на управляющую последовательность около указанной строки и сначала проверьте её имя.','Если имя верно, выясните, какой пакет или определение должно создать эту команду.']};
  if(text.includes('missing $')||text.includes('математический режим')||text.includes('math mode'))return {category:'math-mode',conceptId:'math-mode',plain:'TeX потерял границу между текстовым и математическим режимом. Строка сообщения часто является местом, где несогласованность стала заметна, а не обязательно местом, где она началась.',hints:['Проверьте ближайшие открывающие и закрывающие границы математического режима перед этой строкой.','Сведите фрагмент к одной согласованной паре $…$, \\[ … \\] или математическому окружению.']};
  if(text.includes('extra alignment tab')||text.includes('misplaced alignment')||text.includes('alignment tab'))return {category:'table-alignment',conceptId:'table-cell-separator',plain:'Символ & здесь интерпретируется как структурный разделитель выравнивания. Его количество или положение не соответствует текущей таблице либо математическому окружению.',hints:['Сначала посчитайте смысловые ячейки или точки выравнивания в проблемной строке.','Сопоставьте число & со спецификацией столбцов tabular или структурой align; лишний & нужно убрать либо изменить структуру.']};
  if(text.includes('missing }')||text.includes('runaway argument')||text.includes('фигурн')||text.includes('brace'))return {category:'group-balance',conceptId:'argument',plain:'TeX потерял границу группы или аргумента. Из-за этого всё последующее содержимое может восприниматься как продолжение предыдущей команды.',hints:['Ищите незакрытую группу до строки, где TeX окончательно пожаловался.','Сопоставьте каждую открывающую { с закрывающей } внутри ближайшей команды или определения.']};
  if(text.includes('environment')&&/(undefined|не закрыто|закрыто неверно|mismatch)/.test(text))return {category:'environment-balance',conceptId:'environment',plain:'Окружения образуют вложенную структуру: каждое \\begin{name} должно закрываться соответствующим \\end{name} в правильном порядке, а само окружение должно быть определено.',hints:['Проверьте имя окружения и ближайшую пару begin/end.','Если пара согласована, проверьте пакет или собственное определение, которое должно создавать это окружение.']};
  if(text.includes('file')&&(text.includes('not found')||text.includes('empty')))return {category:'file-reference',conceptId:'multi-file',plain:'TeX не может разрешить внешний ресурс по указанному пути. В проекте путь должен вести к существующему файлу и быть корректным относительно корневого документа.',hints:['Проверьте точное имя файла, расширение и регистр символов.','Проверьте относительный путь от root document и наличие файла в виртуальном проекте.']};
  if(text.includes('bibliograph')||text.includes('citation')||text.includes('biber')||text.includes('bibtex'))return {category:'bibliography-workflow',conceptId:'bibliography-model',plain:'Библиография зависит не только от команды cite: TeX должен видеть ресурс, ключ записи и корректную последовательность библиографической сборки.',hints:['Проверьте, объявлен ли .bib-ресурс и существует ли цитируемый ключ.','Затем проверьте выбранный bibliography backend и то, что полная сборка выполняет необходимый библиографический проход.']};
  if(text.includes('includegraphics')||text.includes('package')||text.includes('amsmath')||text.includes('graphicx'))return {category:'package-placement',conceptId:'package-model',plain:'Команда или окружение зависит от пакета, а пакеты подключаются в преамбуле до начала document.',hints:['Определите, какой пакет предоставляет проблемную команду.','Подключите его через \\usepackage{…} в преамбуле и повторите сборку.']};
  if(text.includes('overfull')||text.includes('underfull'))return {category:'semantic-structure',plain:diagnostic.explanation,hints:['Сначала осмотрите конкретную строку результата и найдите длинный неразрывный фрагмент или неестественный ручной интервал.','Исправьте структуру или допускаемые точки переноса прежде, чем менять размер шрифта или глобальную геометрию.']};
  return {category:'other',plain:diagnostic.explanation,hints:['Начните с самой ранней содержательной ошибки и прочитайте исходник непосредственно перед указанной строкой.','Если причина неочевидна, временно сократите проблемный фрагмент до минимальной конструкции и добавляйте части обратно по одной.']};
}
