import { lazy, Suspense, useEffect, useMemo, useRef, useState, type KeyboardEvent as ReactKeyboardEvent } from 'react';
import { Link, useParams } from 'react-router-dom';
import { BackIcon, BookmarkIcon, PlayIcon } from '../components/Icons';
import { ConceptExercise } from '../components/ConceptExercise';
import { LatexPreview } from '../components/LatexPreview';
import { getExercise, getLesson } from '../data/courses';
import { getExerciseInteraction, initialInteractionValue, interactionLabel } from '../data/exerciseInteractions';
import { compilerFor } from '../services/compiler';
import { validateExercise, type ValidationLevel, type ValidationResult } from '../services/validator';
import { useAppStore } from '../store/useAppStore';
import type { CompilationState, CompileResult, MistakeCategory } from '../types';

const CodeEditor=lazy(()=>import('../components/CodeEditor').then(module=>({default:module.CodeEditor})));
export function PracticeExercisePage(){
  const {exerciseId}=useParams();const exercise=getExercise(exerciseId);const settings=useAppStore(state=>state.settings);const drafts=useAppStore(state=>state.drafts);const setDraft=useAppStore(state=>state.setDraft);const recordAttempt=useAppStore(state=>state.recordExerciseAttempt);const attempts=useAppStore(state=>state.attempts);const recordHint=useAppStore(state=>state.recordHint);const hintsUsed=useAppStore(state=>state.hintsUsed);const bookmarks=useAppStore(state=>state.bookmarks);const toggleBookmark=useAppStore(state=>state.toggleBookmark);
  const interaction=useMemo(()=>exercise?getExerciseInteraction(exercise):({kind:'code'} as const),[exercise]);const draftKey=exercise?`exercise:${exercise.id}`:'';const initial=exercise?initialInteractionValue(exercise,interaction,drafts[draftKey]):'';
  const [source,setSource]=useState(initial);const [result,setResult]=useState<CompileResult|null>(null);const [validation,setValidation]=useState<ValidationResult|null>(null);const [compileState,setCompileState]=useState<CompilationState>('ready');const [solution,setSolution]=useState(false);const [saved,setSaved]=useState(true);const [shortcutsOpen,setShortcutsOpen]=useState(false);const shortcutRef=useRef<HTMLElement>(null);const restoreShortcutFocus=useRef<HTMLElement|null>(null);
  const hintLevel=exercise?(hintsUsed[exercise.id]??0):0;const conceptual=interaction.kind!=='code';
  useEffect(()=>{if(!exercise)return;setSource(initialInteractionValue(exercise,interaction,drafts[`exercise:${exercise.id}`]));setResult(null);setValidation(null);setSolution(false);setCompileState('ready');setSaved(true);const key=`latex-gym:scroll:${exercise.id}`;const restored=Number(sessionStorage.getItem(key)??0);requestAnimationFrame(()=>window.scrollTo({top:restored,behavior:'auto'}));return()=>{sessionStorage.setItem(key,String(window.scrollY));};},[exercise?.id,interaction]);
  useEffect(()=>{if(!exercise)return;setSaved(false);const id=window.setTimeout(()=>{setDraft(`exercise:${exercise.id}`,source);setSaved(true);},280);return()=>window.clearTimeout(id);},[source,exercise?.id,setDraft]);
  useEffect(()=>{if(!shortcutsOpen)return;restoreShortcutFocus.current=document.activeElement instanceof HTMLElement?document.activeElement:null;const frame=requestAnimationFrame(()=>shortcutRef.current?.querySelector<HTMLElement>('button,[href],input,select,textarea,[tabindex]:not([tabindex="-1"])')?.focus());const onKey=(event:KeyboardEvent)=>{if(event.key==='Escape'){event.preventDefault();setShortcutsOpen(false);}};document.addEventListener('keydown',onKey);return()=>{cancelAnimationFrame(frame);document.removeEventListener('keydown',onKey);restoreShortcutFocus.current?.focus();};},[shortcutsOpen]);
  const lesson=useMemo(()=>exercise?getLesson(exercise.lessonId):undefined,[exercise]);const position=useMemo(()=>Math.max(1,(lesson?.exercises.findIndex(item=>item.id===exercise?.id)??0)+1),[lesson,exercise?.id]);const total=lesson?.exercises.length??1;
  if(!exercise)return <div className="page empty-state">Задача не найдена.</div>;
  const isSaved=bookmarks.some(item=>item.type==='exercise'&&item.targetId===exercise.id);const busy=compileState==='queued'||compileState==='compiling';
  const setExerciseSource=(value:string)=>{setSource(value);if(validation)setValidation(null);if(result&&conceptual)setResult(null);};const saveNow=()=>{setDraft(`exercise:${exercise.id}`,source);setSaved(true);};const reset=()=>setExerciseSource(initialInteractionValue(exercise,interaction));
  const runCompile=async()=>{if(conceptual)return null;setCompileState('queued');setValidation(null);await Promise.resolve();setCompileState('compiling');try{const compiled=await compilerFor(exercise.compilerRequirement).compile(source);setResult(compiled);if(!compiled.ok)setCompileState('error');else if(compiled.diagnostics.some(item=>item.severity==='warning'))setCompileState('warning');else setCompileState('success');return compiled;}catch{setCompileState('error');return null;}};
  const recordCheckedAttempt=(checked:ValidationResult,compiled?:CompileResult|null)=>{
    const categories=[...checked.items.filter(item=>!item.ok&&item.mistakeCategory).map(item=>item.mistakeCategory!),...(compiled?.diagnostics??[]).filter(item=>item.severity==='error'&&item.mistakeCategory).map(item=>item.mistakeCategory!)] as MistakeCategory[];
    recordAttempt(exercise.id,checked.ok,exercise.concepts,exercise.title,{firstTry:(attempts[exercise.id]??0)===0,hintsUsed:hintLevel,solutionRevealed:solution,mistakeCategories:[...new Set(categories)]});
  };
  const check=async()=>{if(conceptual){const checked=validateExercise(exercise,source);setValidation(checked);recordCheckedAttempt(checked);return;}const compiled=await runCompile();if(!compiled)return;const checked=validateExercise(exercise,source,compiled);setValidation(checked);recordCheckedAttempt(checked,compiled);};
  const revealHint=()=>{const next=Math.min(exercise.hints.length,hintLevel+1);recordHint(exercise.id,next);};
  const renderHints=(variant:'desktop'|'mobile')=><div className={`hint-area hint-area--${variant}`}><div className="hint-heading"><span>Подсказки</span><button onClick={revealHint} disabled={hintLevel>=exercise.hints.length}>{hintLevel>=exercise.hints.length?'Все открыты':'Открыть подсказку'}</button></div>{exercise.hints.slice(0,hintLevel).map((hint,index)=><p key={index}><b>{index+1}.</b> {hint}</p>)}{hintLevel>=exercise.hints.length&&!solution&&<button className="text-tool reveal-solution" onClick={()=>setSolution(true)}>Показать эталонное решение</button>}</div>;
  const blockingItems=validation?.items.filter(item=>item.blocking)??[];const passed=blockingItems.filter(item=>item.ok).length;const advisoryCount=validation?.items.filter(item=>!item.blocking&&!item.ok).length??0;
  return <div className="practice-screen" data-compilation-state={compileState}>
    <header className="practice-top"><Link to="/practice" aria-label="Назад к практике"><BackIcon/></Link><strong>Практика</strong><button type="button" className={`icon-button practice-bookmark ${isSaved?'active':''}`} onClick={()=>toggleBookmark('exercise',exercise.id)} aria-label={isSaved?'Удалить задачу из закладок':'Сохранить задачу'}><BookmarkIcon/></button></header>
    <div className="practice-workspace"><section className="task-pane"><div className="task-progress"><span>ЗАДАНИЕ {position} ИЗ {total}</span><div><i style={{width:`${(position/total)*100}%`}}/></div></div><span className="practice-mode">{interactionLabel(interaction,exercise.mode)}</span><h1>{exercise.instructions}</h1><p className="requirements-title">Требования:</p><ul>{exercise.requirements.map(requirement=><li key={requirement}>{requirement}</li>)}</ul>{renderHints('desktop')}</section>
      <section className="editor-pane mobile-active"><div className="editor-pane-inner"><div className="editor-status-line"><span className={`compile-state ${conceptual?'':'compile-state--'+compileState}`}>{conceptual?'Ответ без компиляции':stateLabel(compileState)}</span><span>{saved?'Сохранено локально':'Сохранение…'}</span></div>{conceptual?<ConceptExercise interaction={interaction} value={source} onChange={setExerciseSource} disabled={busy}/>:<Suspense fallback={<div className="editor-loading">Загрузка редактора…</div>}><CodeEditor value={source} onChange={setExerciseSource} wordWrap={settings.wordWrap} showLineNumbers={settings.lineNumbers} autoClose={settings.autoClose} minHeight={235} onReset={reset} onCompile={()=>{void runCompile();}} onSave={saveNow} onShowShortcuts={()=>setShortcutsOpen(true)} diagnostics={result?.diagnostics??[]}/></Suspense>}{!conceptual&&<button className="compile-button" onClick={()=>{void runCompile();}} disabled={busy}><PlayIcon/>{busy?'Компиляция…':'Скомпилировать'}</button>}</div></section>
      <section className="result-pane mobile-active"><h2>{conceptual?'Проверка':'Результат'}</h2>{!conceptual&&<div className="result-frame"><LatexPreview result={result}/></div>}{conceptual&&!validation&&<div className="conceptual-note"><h3>Здесь компиляция не нужна.</h3><p>Задание проверяет понимание модели LaTeX, а не умение вводить ответ в редактор исходника.</p></div>}{!conceptual&&result&&!validation&&<div className="compile-result-note" role="status" aria-live="polite"><h3>{result.ok?'Документ собирается.':'Компиляция остановлена.'}</h3><p>{result.ok?(result.engine==='wasm-tex'?'Исходник действительно прошёл TeX-сборку. Задание ещё нужно проверить по смысловым критериям.':'Задание ещё не проверено. Компиляция отвечает только на вопрос, может ли учебный preview обработать исходник.'):'Исправьте первую содержательную ошибку и запустите компиляцию снова.'}</p></div>}{validation&&<div className={`validation-panel ${validation.ok?'validation-panel--ok':''}`} role="status" aria-live="polite"><h3>{validation.ok?(advisoryCount?`Решение принято · замечаний: ${advisoryCount}`:'Решение принято'):`Выполнено ${passed} из ${blockingItems.length} требований`}</h3>{validation.items.map((item,index)=><div className={`validation-row validation-row--${item.level}`} key={index}><span>{item.ok?'✓':item.blocking?'×':'!'}</span><div><strong>{item.message}</strong><small>{validationLevelLabel(item.level)}{item.line?` · строка ${item.line}`:''}</small>{!item.ok&&<small>{item.hint}</small>}</div></div>)}</div>}{solution&&<details className="reference-solution" open><summary>Эталонное решение</summary><pre>{exercise.solution}</pre><p>Это один корректный вариант; проверка основана на требованиях, а не на полном совпадении строки.</p></details>}{renderHints('mobile')}</section></div>
    <footer className="practice-action"><button className="primary-button primary-button--large" onClick={()=>{void check();}} disabled={busy}>{conceptual?'Проверить ответ':'Проверить решение'}</button></footer>
    {shortcutsOpen&&<div className="shortcut-backdrop" role="presentation" onMouseDown={()=>setShortcutsOpen(false)}><section ref={shortcutRef} className="shortcut-dialog" role="dialog" aria-modal="true" aria-labelledby="shortcut-title" onMouseDown={event=>event.stopPropagation()} onKeyDown={event=>{if(event.key==='Tab')trapTab(event,shortcutRef.current);}}><button className="shortcut-close" onClick={()=>setShortcutsOpen(false)} aria-label="Закрыть">×</button><span className="eyebrow">РЕДАКТОР</span><h2 id="shortcut-title">Клавиатура</h2><dl><div><dt>Cmd/Ctrl + Enter</dt><dd>Скомпилировать</dd></div><div><dt>Cmd/Ctrl + S</dt><dd>Сохранить локальный черновик</dd></div><div><dt>Cmd/Ctrl + K</dt><dd>Поиск LaTeX gym</dd></div><div><dt>Cmd/Ctrl + /</dt><dd>Эта справка</dd></div></dl></section></div>}
  </div>;
}
function stateLabel(state:CompilationState){if(state==='queued')return 'В очереди';if(state==='compiling')return 'Компиляция';if(state==='success')return 'Документ собирается';if(state==='warning')return 'Документ собирается с предупреждением';if(state==='error')return 'Компиляция остановлена';return 'Готов к компиляции';}
function validationLevelLabel(level:ValidationLevel){if(level==='warning')return 'WARNING';if(level==='style')return 'STYLE';if(level==='pedagogy')return 'PEDAGOGICAL NOTE';return 'ТРЕБОВАНИЕ';}
function trapTab(event:ReactKeyboardEvent,container:HTMLElement|null){if(!container)return;const focusable=[...container.querySelectorAll<HTMLElement>('button,a[href],input,select,textarea,[tabindex]:not([tabindex="-1"])')].filter(element=>!element.hasAttribute('disabled')&&element.getAttribute('aria-hidden')!=='true');if(!focusable.length){event.preventDefault();return;}const first=focusable[0],last=focusable[focusable.length-1];if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus();}}
