import { useRef, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { getRuntimeLesson } from '../data/runtimeCatalog';
import { exportProgress, useAppStore } from '../store/useAppStore';
export function SettingsPage(){
  const navigate=useNavigate();const settings=useAppStore(s=>s.settings);const update=useAppStore(s=>s.updateSettings);const reset=useAppStore(s=>s.resetProgress);const retakeOnboarding=useAppStore(s=>s.retakeOnboarding);const onboarding=useAppStore(s=>s.onboarding);const importProgress=useAppStore(s=>s.importProgress);const input=useRef<HTMLInputElement>(null);const [message,setMessage]=useState('');
  const recommendedLesson=onboarding.recommendedLessonId?getRuntimeLesson(onboarding.recommendedLessonId):undefined;
  const download=async()=>{const blob=new Blob([await exportProgress()],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='latex-gym-progress.json';a.click();URL.revokeObjectURL(url);};
  const upload=async(file?:File)=>{if(!file)return;const response=await importProgress(await file.text());setMessage(response.message);};
  const retake=()=>{retakeOnboarding();navigate('/');};
  return <div className="page editorial-page settings-page"><header className="page-intro"><span className="eyebrow">НАСТРОЙКИ</span><h1>Интерфейс обучения</h1><p>Параметры чтения, редактора, диагностики уровня и локальных данных. Учётная запись приложению не требуется.</p></header>
    <section className="settings-section"><h2>Тема</h2><div className="setting-row"><span><strong>Светлая</strong><small>Основная академическая тема LaTeX Gym</small></span><span className="setting-value">FAFAF8</span></div></section>
    <section className="settings-section"><h2>Размер текста</h2><div className="segmented">{(['small','medium','large'] as const).map((v,i)=><button className={settings.textSize===v?'active':''} key={v} onClick={()=>update({textSize:v})}>{['Маленький','Средний','Крупный'][i]}</button>)}</div></section>
    <section className="settings-section"><h2>Редактор</h2><label className="toggle-row"><span>Перенос строк</span><input type="checkbox" checked={settings.wordWrap} onChange={e=>update({wordWrap:e.target.checked})}/></label><label className="toggle-row"><span>Автозакрытие скобок</span><input type="checkbox" checked={settings.autoClose} onChange={e=>update({autoClose:e.target.checked})}/></label><label className="toggle-row"><span>Номера строк</span><input type="checkbox" checked={settings.lineNumbers} onChange={e=>update({lineNumbers:e.target.checked})}/></label></section>
    <section className="settings-section"><h2>Диагностика уровня</h2><div className="setting-row"><span><strong>{onboarding.placementScore===null?'Не пройдена':`${onboarding.placementScore} / ${onboarding.placementTotal}`}</strong><small>{recommendedLesson?`Рекомендованный старт: ${recommendedLesson.title}`:'Можно пройти короткую адаптивную проверку практических навыков.'}</small></span><button className="secondary-button" onClick={retake}>Пройти заново</button></div></section>
    <section className="settings-section"><h2>Локальные данные</h2><div className="settings-actions"><button className="secondary-button" onClick={()=>{void download();}}>Экспорт прогресса</button><button className="secondary-button" onClick={()=>input.current?.click()}>Импорт прогресса</button><input ref={input} type="file" accept="application/json" hidden onChange={e=>{void upload(e.target.files?.[0]);}}/><button className="danger-link" onClick={()=>{if(window.confirm('Сбросить весь локальный прогресс?'))reset()}}>Сбросить прогресс</button></div>{message&&<p className="settings-message" role="status">{message}</p>}</section>
  </div>;
}
