import { StrictMode } from 'react';
import { createRoot } from 'react-dom/client';
import { registerSW } from 'virtual:pwa-register';
import './data/editorialEnhancements';
import './data/curriculumExpansion';
import './data/deepCurriculum';
import './data/debuggingTrack';
import { App } from './app/App';
import './styles/index.css';
import './styles/fidelity.css';
import './styles/deviceLayouts.css';
import './styles/laptopPolish.css';
import './styles/deepProduct.css';
import './styles/smartEditor.css';
import './styles/projects.css';
import './styles/projectWorkspace.css';
import './styles/referenceDeep.css';
import './styles/progressDeep.css';
import './styles/interactionPolish.css';
import './styles/conceptExercises.css';

registerSW({ immediate: true });
createRoot(document.getElementById('root')!).render(<StrictMode><App/></StrictMode>);
